name: My First Workflow

on:
  push:

jobs:
  first-job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: List And Read Files
        run: |
          echo "Welcome"
          ls -ltra
          cat README.md
      
      - name: ASCII Art Work
        run: |
          cowsay -f dragon "Run For Cover, I am Dragon..." > dragon.txt