name: Generate ASCII ArtWork

on: push

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install -y cowsay
      
      - name: Execute Cowsay Cmd
        run: cowsay -f dragon "Runfor your life.....I am DRAGON" > dragon.txt
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ascii-artifact
          path: dragon.txt

  test-job:
    runs-on: ubuntu-latest
    needs: [build-job]
    steps:
      - name: Download ASCII Artifact
        uses: actions/download-artifact@v8
        with:
          name: ascii-artifact
      
      - name: Test File Exists
        run: grep -i 'dragon' dragon.txt

  deploy-job:
    runs-on: ubuntu-latest
    needs: [test-job]
    steps:
      - name: Download ASCII Artifact
        uses: actions/download-artifact@v8
        with:
          name: ascii-artifact
          
      - name: Read File
        run: cat dragon.txt

      - name: Deploy
        run: echo "Deploying..."