name: Generate ASCII ArtWork

on: push

jobs:
  acii_job:
    name: ASCII Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: List Files
        run: ls -ltra

      - name: Executing Shell Script
        run: ./ascii-art.sh